[toolchain]
cxx_compiler = 'clang++'
c_compiler = 'clang'
linker = 'mold'

[deps]
packages = [
    "gh:fmtlib/fmt#9.1.0",
    "gh:catchorg/Catch2@3.3.2",
]

link_names = [
    "fmt::fmt"
]

link_tests = [
    "Catch2::Catch2WithMain"
]
