set(MOLD_FLAG "-fuse-ld=mold")
check_cxx_compiler_flag(${MOLD_FLAG} CXX_SUPPORTS_USER_LINKER)
if(CXX_SUPPORTS_USER_LINKER)
  set(LINK_OPTIONS ${MOLD_FLAG})
  message(STATUS "Set linker flag ${MOLD_FLAG}")
elseif()
  message(STATUS "Failed to use mold")
endif()